# 浏览器配置
browser:
  headless: true
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  window_size:
    width: 1920
    height: 1080
  page_load_timeout: 30
  implicit_wait: 10

# 爬虫配置
crawler:
  max_pages: 100  # 最大测试页面数，null表示无限制
  delay: 1  # 页面间延迟（秒）
  max_retries: 3  # 失败重试次数
  excluded_patterns:
    - "logout"
    - "delete"
    - "remove"
    - ".pdf"
    - ".doc"
    - ".xls"

# 错误检测配置
error_detection:
  http_error_codes:
    - 400
    - 401
    - 403
    - 404
    - 500
    - 502
    - 503
    - 504
  error_keywords:
    - "error"
    - "Error"
    - "错误"
    - "异常"
    - "失败"
    - "warning"
    - "Warning"
    - "警告"

# 报告配置
reporting:
  output_dir: "test_results"
  formats:
    - json
    - excel
    - html
  screenshot_on_error: true
  save_page_source: true
  log_level: "INFO" 